#!/bin/sh
source ~/.config/panel/panel.cfg

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &

xtitle -sf 'T%s' > "$PANEL_FIFO" &

# date & time title sie odswieza i dodaje date tylko jak zmieniam title, po prawej data sie nie wyswietla bez c
while true; do
     date +"c%A %x | %H:%M:%S"
     sleep 1
     done > "$PANEL_FIFO" &

while true; do
	interface=$WIFI_DEV
    BitRate=`sudo iwconfig $interface | grep 'Bit Rate=' | awk '{gsub(/[=/]/," "); print $3}'`
    ESSID=`sudo iwconfig $interface | grep "ESSID:" | awk '{gsub(/[:"]/," "); print $5}'`
    echo "w$ESSID - $BitRate Mb/s"
    sleep 300
    done > "$PANEL_FIFO" &

cat "$PANEL_FIFO" | ~/.config/panel/panel_bar | lemonbar -g ${BARWIDTH}x${BARHEIGHT}+${EDGEWIDTH} /
							-f "$PANEL_FONT_1" /
							-F "$FOREGROUND" /
							-B "$BACKGROUND" /
							-u "$UNDERLINE_WIDTH" | /
while read line; do eval "$line"; done & wait
