#!/bin/sh

# how long should the popup remain?
pop_dur=2

# define geometry
popx=1400
popy=20
popw=60
poph=40

# colors
pop_bg='#2d2d2d'
pop_fg='#dedede'

# font used
pop_font='Hasklig:size=9'
# docking is necessary with bspwm, otherwise it pushes the windows around 
popopt='-d -g '${popw}'x'${poph}'+'${popx}'+'${popy}' -B '${pop_bg}' -F '${pop_fg}' -f '${pop_font}' '
# @ is all arguments, so I can pass it to a script
# Create the popup and make it live for 3 seconds
#(echo " $@"; sleep ${duration}) | lemonbar ${popopt}
batcap=/sys/class/power_supply/BAT0/capacity
valcap=$(cat $batcap)
test "`cat $batstat`" = "Discharging" && symbol='-' || symbol='+'

(echo "%{c}$symbol$valcap"; sleep ${pop_dur}) | lemonbar ${popopt}

