#!/bin/sh
. ~/.config/panel/config
# how long should the popup remain?
pop_dur=3

# define geometry
popx=177
popy=0
popw=1120
poph=16

# colors
pop_bg='#2d2d2d'
#pop_bg='#525252'
pop_fg='#d64937'
#${HOME}/.config/panel/notifications/popitup_vol2 
# font used
PANEL_FONT1='Source Code Pro:size=10'
PANEL_FONT2='Hasklig:size=10'
PANEL_FONT3='DejaVu Sans Mono:Size:20'
# docking is necessary with bspwm, otherwise it pushes the windows around 
popopt='-d -g '${popw}'x'${poph}'+'${popx}'+'${popy}' -B '${pop_bg}' -F '${pop_fg}' -f '${PANEL_FONT2}' -f '${PANEL_FONT3}' '
# @ is all arguments, so I can pass it to a script
# for example I could call a generic popup and pass the values via parameters instead of crafting new popup for every single thing
# Create the popup and make it live for 3 seconds
#(echo " $@"; sleep ${duration}) | lemonbar ${popopt}
(echo -e "%{c}${1}"; sleep ${pop_dur}) | lemonbar ${popopt}

#(echo -e "%{R}%{c}${1}"; sleep ${pop_dur}) | lemonbar ${popopt}
