#!/bin/dash
DEBUG=${DEBUG:-true}
if [ $DEBUG = true ]; then
    set -x
    exec 2>> "/tmp/bspwm_exrules.log"
    date >&2
fi
wid=$1 class=$2 instance=$3
eval $4
case $class in
    URxvt)
        case "$(xprop -id "$wid" WM_NAME | cut -d\" -f2)" in
            "urxvt")
                rule="${rule}state=floating "; state=floating
                ;;
        esac
        ;;
esac
[ $DEBUG ] && notify-send "$(xtitle $wid)" "${rule:-no rules set}"
[ -n "$rule" ] && echo "$rule"
