#!/usr/bin/env dash

# https://www.reddit.com/r/bspwm/comments/g6bbcz/how_can_i_resize_windows_with_one_key_combination/
direction="$1"
sense="$2"

# countersense is a real word, right?
if [ "$sense" = "+" ]; then
	countersense="-"
else
	countersense="+"
fi

# First we try to resize using the bottom/right borders. If this fails (e.g. tiled) we fall back to top/left.
if [ "$direction" = "x" ]; then
	bspc node --resize "right" "${sense}20" "0" ||
	bspc node --resize "left" "${countersense}20" "0"
else
	bspc node --resize "bottom" "0" "${sense}20" ||
	bspc node --resize "top" "0" "${countersense}20"
fi
