#! /bin/sh

source $(dirname $0)/config
. panel_colors

while read -r line ; do
    case $line in
        S*)
            sys_infos="%{r} ${line#?} "
# clock output
#            sys_infos="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}%{r} ${line#?} %{B-}%{F-}"
            ;;
        T*)
            title="%{F$COLOR_ICON}%{F-} ${line#?} "
#	    title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"

            ;;
        W*)
           # wm_infos="%{c}"
	    wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    [OFU]*)
                        # active desktop
                        wm_infos="$wm_infos %{U$COLOR_ACTIVE}%{+u} ${name} %{-u}"
                        ;;
                    o*)
                        # inactive but occupied desktop
                        wm_infos="$wm_infos %{U$COLOR_OCCUPIED}%{+u} ${name} %{-u}"
                        ;;
                    f*)
                        # inactive desktop
                        wm_infos="$wm_infos  ${name} "
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="$wm_infos %{U$COLOR_URGENT}%{+u} ${name} %{-u}"
                        ;;
                    L*)
                        # layout
#                        layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
                        wm_infos="$wm_infos $layout"
                        ;;
                esac
                shift
            done
            ;;
    esac
#	printf "%s\n" "$title$wm_infos$sys_infos"
     printf "%s\n" "%{c}${wm_infos}%{l}${title}%{r}${sys_infos}"
done

