#! /bin/sh

cd $(dirname $0)
source $(dirname $0)/config
source panel_colors

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc subscribe > "$PANEL_FIFO" &

echo "T" >  "$PANEL_FIFO" &
#conky -c ./panel_conky > "$PANEL_FIFO" &
#./notify_mpd -d &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &

cat "$PANEL_FIFO" \
	| panel_bar \
	| bar \
		-f "$FONT1","$FONT2" \
		-F "$COLOR_FOREGROUND" \
		-B "$COLOR_BACKGROUND" \
		-g "$PANEL_GEOMETRY" \
		-u "$LINEHEIGHT" &

#cat "$PANEL_FIFO" | panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$PANEL_FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &
wait
