#! /bin/sh
# bspc config honor_size_hints true
bspc config top_padding                 14
bspc config border_width                2
bspc config window_gap                  10
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_by_distance           true
# follows pointer
bspc config focus_follows_pointer       true

bspc config normal_border_color         "#332d29"
bspc config active_border_color         "#817267"
bspc config focused_border_color        "#504339"
#bspc config presel_border_color         "#9a875f"
#bspc config urgent_border_color         "#9f7155"
#bspc config focused_locked_border_color "#9a875f"
#bspc config normal_frame_opacity        0.0
#bspc config focused_frame_opacity       0.1
# stay in your desktop?
#bspc config ignore_ewmh_focus 		true
#bspc monitor DVI-I-1 -d o o o o
#bspc monitor HDMI-0 -d o o o o
i=1
#for every monitor in the following command, assign workspaces for each
# bspc monitor $monitor (for example 0x00800003) -n (i dont know what that is) -d (draw workspaces)
for monitor in $(bspc query -M);
    do
        bspc monitor $monitor \
        -n "$i" \
        -d {o,o,o,o}
        let i++
    done
bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Google-chrome desktop=^2 state=floating follow=off
bspc rule -a steam desktop=^2 split_dir=right follow=off
bspc rule -a mplayer2 floating=on
bspc rule -a keepassxc desktop =^4
bspc rule -a firefox desktop=^3
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a feh floating=on manage=off
# fix for cursor not changing
# not sure whether to put it here ot in xinitrc
#sh ~/.fehbg &
xsetroot -cursor_name left_ptr &
#welcome urxvt with gentoo logo
urxvt -e bash -c "screenfetch -d '-shell'; bash" &
sxhkd -c ${HOME}/.config/sxhkd/sxhkdrc &
${HOME}/.config/panel/panel &
compton --config ${HOME}/.compton.conf &
