#!/bin/sh
git clone --bare git@github.com:Vaernil/my-dotfiles.git $HOME/.cfg
cfg
{
	/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME $@
}
now=$(date +"%Y-%m-%d_%H-%M")
mkdir -p .dotfiles-backup/$now
cfg checkout
if [ $? = 0 ]; then
	echo "Checked out cfg.";
else
	echo "Backing up pre-existing .dotfiles.";
	cfg checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .dotfiles-backup/{}
fi;
cfg checkout
cfg config status.showUntrackedFiles no
echo "Untracked files hidden.";
