#!/bin/sh
# fix later
#fatal: destination path '/home/vaernil/.cfg' already exists and is not an empty directory.
# WIP doesn't work for now
if [ -e "$HOME/.cfg" ]; then
	while read line
	do
#		echo ".cfg exists - remove? [Y/n]:";
		read -p '.cfg exists - remove? [Y/n]: ' prompt_remove </dev/tty
		case "${prompt_remove}" in
		Y|y)
			# remove and clone repository
			rm -rf ~/.cfg
			git clone --bare git@github.com:Vaernil/my-dotfiles.git $HOME/.cfg
			#continue
			break
			;;
		*)
			echo "OK. Bye!"
			echo "Script can't continue, either rename or remove .cfg folder."
			#break
			exit
			;;
		esac
	done
else
	git clone --bare git@github.com:Vaernil/my-dotfiles.git $HOME/.cfg
fi

cfg
{
	/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME $@
}
now=$(date +"%Y-%m-%d_%H-%M")
mkdir -p .dotfiles-backup/$now
cfg checkout
if [ $? = 0 ]; then
	echo "Checked out cfg."
else
	echo "Backing up pre-existing .dotfiles."
	cfg checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .dotfiles-backup/{}
fi
cfg checkout
cfg config status.showUntrackedFiles no
echo "Untracked files hidden."
